/*
 * Copyright © 2019-today Peter M. Stahl pemistahl@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
//
//   ucd-generate general-category ucd-15.0.0 --chars --include decimalnumber
//
// Unicode version: 15.0.0.
//
// ucd-generate 0.3.0 is available on crates.io.

pub const DECIMAL_NUMBER: &[(char, char)] = &[
    ('0', '9'),
    ('٠', '٩'),
    ('۰', '۹'),
    ('߀', '߉'),
    ('०', '९'),
    ('০', '৯'),
    ('੦', '੯'),
    ('૦', '૯'),
    ('୦', '୯'),
    ('௦', '௯'),
    ('౦', '౯'),
    ('೦', '೯'),
    ('൦', '൯'),
    ('෦', '෯'),
    ('๐', '๙'),
    ('໐', '໙'),
    ('༠', '༩'),
    ('၀', '၉'),
    ('႐', '႙'),
    ('០', '៩'),
    ('᠐', '᠙'),
    ('᥆', '᥏'),
    ('᧐', '᧙'),
    ('᪀', '᪉'),
    ('᪐', '᪙'),
    ('᭐', '᭙'),
    ('᮰', '᮹'),
    ('᱀', '᱉'),
    ('᱐', '᱙'),
    ('꘠', '꘩'),
    ('꣐', '꣙'),
    ('꤀', '꤉'),
    ('꧐', '꧙'),
    ('꧰', '꧹'),
    ('꩐', '꩙'),
    ('꯰', '꯹'),
    ('０', '９'),
    ('𐒠', '𐒩'),
    ('𐴰', '𐴹'),
    ('𑁦', '𑁯'),
    ('𑃰', '𑃹'),
    ('𑄶', '𑄿'),
    ('𑇐', '𑇙'),
    ('𑋰', '𑋹'),
    ('𑑐', '𑑙'),
    ('𑓐', '𑓙'),
    ('𑙐', '𑙙'),
    ('𑛀', '𑛉'),
    ('𑜰', '𑜹'),
    ('𑣠', '𑣩'),
    ('𑥐', '𑥙'),
    ('𑱐', '𑱙'),
    ('𑵐', '𑵙'),
    ('𑶠', '𑶩'),
    ('𑽐', '𑽙'),
    ('𖩠', '𖩩'),
    ('𖫀', '𖫉'),
    ('𖭐', '𖭙'),
    ('𝟎', '𝟿'),
    ('𞅀', '𞅉'),
    ('𞋰', '𞋹'),
    ('𞓰', '𞓹'),
    ('𞥐', '𞥙'),
    ('🯰', '🯹'),
];
